# Generated by Django 4.1.4 on 2023-01-03 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_blogdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogDate',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogDateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 17, 5, 21, 490149)),
        ),
    ]
