# Generated by Django 4.1.4 on 2023-01-03 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_blogdate_blogpost_blogdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blogMonth',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogYear',
            field=models.IntegerField(default=2023, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blogDateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 18, 46, 28, 634632)),
        ),
    ]
